### ISSUE TITLE
Cannot destructure property 'errors' of 'object null' as it is null.

### ISSUE THREAD

**Issue by swathisham** [mfrachet/cypress-audit#106]
Seeing this error mentioned in https://githubmemory.com/repo/mfrachet/cypress-audit/issues/74
![image](https://user-images.githubusercontent.com/16354764/135735310-061bac77-1de3-4ff4-95ad-d03608dc94b0.png)

**Comment by mfrachet** [comment]
Thank you for filling this issue.

Without any additional context and according to the fact that you didn't take time to fill the bug template to provide meaningful information about your setup, I will close this issue without even investigating.

If you're interested in seeing this bug fix, please, create an issue with the required informations.

**Comment by jblotus** [comment]
I have the same error. This only seems to happen when I supply threshold property to the cy.lighthouse() command.

```
cy.visit('/');
cy.lighthouse({
    performance: 85,
    "first-contentful-paint": 2000,
});
```

**Comment by jblotus** [comment]
I apologize, I was getting the error regardless of setting this option.  I think what ended up happening was the tab that is normally spawned to perform the audits was failing to spawn for some reason.  I closed out of the spec (I'm in open mode) and reloaded it and it ran just fine.
