### ISSUE TITLE
Browser variable has typescript error if config in plugins/index is typed.

### ISSUE THREAD

**Issue by aaron-goff** [mfrachet/cypress-audit#115]
_Before creating an issue, make sure to have setup the projects with the **3** steps provided in the README. You can also verify the examples folder and check if there is already an application using a similar setup to yours._

**What does not work?**
If the `config` in the `module.exports` within `plugins/index.ts` is typed (appropriately as `Cypress.PluginConfig`, then TypeScript will give the following error:
```
Type '{}' is missing the following properties from type 'Browser': name, family, channel, displayName, and 5 more.
```

**How to reproduce?**
1. Install TypeScript and Cypress (via `npm install --save-dev typescript cypress`)
2. Configure your `.tsconfig.json` file to scan your Cypress files (most easily done by using `"include": ["**/*.*"]`
3. Set up `plugins/index.ts` file as specified in README.
4. Type `on` and `config` variables as `Cypress.PluginEvents` and `Cypress.PluginConfigOptions`, respectively
5. If necessary, restart your TypeScript server and run `tsc` or `npx tsc` from your project's root

**Expected behavior**
`browser` variable is correctly typed (or rather, there is documentation on how to correctly type this variable)

**Screenshots / Animated Gifs**
![Screen Shot 2021-11-03 at 12 37 15 PM](https://user-images.githubusercontent.com/38787594/140103741-cd12d414-6b80-433a-98ef-25b88f6ae9a4.png)
![Screen Shot 2021-11-03 at 12 37 33 PM](https://user-images.githubusercontent.com/38787594/140103765-60be6a1d-a98b-417d-b399-f02d7cc2c95c.png)
![image](https://user-images.githubusercontent.com/38787594/140103832-904c14be-4bf8-497b-aec3-d64484a4fe58.png)

**Environment (please complete the following information):**
 - OS: MacOS 11.6
 - Chrome version: 94
 - Cypress version: 8.6.0

**Any other information that may help fixing the issue?**
I understand that this library does not explicitly support TypeScript, but at the very least it shouldn't cause any TS errors when attempting to use it with TS. Really just any documentation on how to type out that `browser` object would probably solve the problem.
Additionally, type is not given for `launchOptions`. This can be resolved by just declaring an `any` type (sort of defeats the purpose of TS though 😂 ).
I tried setting `browser = Cypress.browser` but I receive an `INVALID_URL` error when running the test.

Any guidance would be greatly appreciated

**Comment by aaron-goff** [comment]
This was completely a user error -- I had some other things going on that were causing the `INVALID_URL` error when doing `browser = Cypress.browser`. I can successfully set the `browser` variable. Apologies for any confusion.

**Comment by hiendnguyen** [comment]
@aaron-goff how did you solve the issue, please? I got exactly the same error.

**Comment by aaron-goff** [comment]
I was able to get around this by setting by `browser` variable equal to `Cypress.browser`
```javascript
on('before:browser:launch', (browser = Cypress.browser, launchOptions: any) => { ... })
```

**Comment by hiendnguyen** [comment]
Thank you very much @aaron-goff, I really do appreciate you taking the time to reply to my question.

I have  to use `_browser = Cypress.browser` instead to get rid off error `browser is declared but its value is never used`
