### ISSUE TITLE
Upgrade lighthouse 

### ISSUE THREAD

**Issue by mfrachet** [mfrachet/cypress-audit#12]
Lighthouse 6 is out: https://github.com/GoogleChrome/lighthouse

**Comment by blatinier** [comment]
It's out! https://www.npmjs.com/package/lighthouse

Changelog: https://github.com/GoogleChrome/lighthouse/releases
Nothing will break from what I saw.

**Comment by mfrachet** [comment]
Yeees! Thanks for this! I'm going to investigate potential improvements here also 😊

**Comment by mfrachet** [comment]
https://github.com/mfrachet/cypress-audit/pull/19

For now its just a bump of lighthouse. Will probably investigate after that
