### ISSUE TITLE
Is there a way to add configuration in Cypress.json ?

### ISSUE THREAD

**Issue by gurudattgd04** [mfrachet/cypress-audit#124]
Hello, 

I see we can add threshold in the cypress.json in below way

"lighthouse": {
    "performance": 85,
    "accessibility": 80,
    "best-practices": 85,
    "seo": 85,
    "pwa": 50
  }

But is there a way that I can add configuration too in cypress.json rather than test level? like below
{"formFactor":"desktop",
    "screenEmulation": {
    "width": 1350,
    "height": 940,
    "deviceScaleRatio": 1,
    "mobile": false,
    "disable": false
  }}

Thanks for the help

**Comment by mfrachet** [comment]
no, it's not possible in the actual version of the tool :/
