### ISSUE TITLE
An unexpected error while trying to run the tests

### ISSUE THREAD

**Issue by VitalyAdweek** [mfrachet/cypress-audit#149]
_Before creating an issue, make sure to have setup the projects with the **3** steps provided in the README. You can also verify the examples folder and check if there is already an application using a similar setup to yours._

**What does not work?**
Error in runner when adding `const { lighthouse, prepareAudit } = require("@cypress-audit/lighthouse"); `
to `cypress/plugins/index.js`

**How to reproduce?**
1. add 
`const { lighthouse, prepareAudit } = require("@cypress-audit/lighthouse"); `
to 
`cypress/plugins/index.js`

2. in terminal:
` npx cypress open`

**Expected behavior**
Runner should show available test suites

**Screenshots / Animated Gifs**
<img width="1018" alt="Screen Shot 2022-04-20 at 5 42 17 PM" src="https://user-images.githubusercontent.com/82416786/164327920-d298b78e-ebae-4497-8b5d-8114fc1726c1.png">

**Environment (please complete the following information):**
 - OS: MAC 12.3.1 (21E258)
 - Chrome version: 100.0.4896.127
 - Cypress version: 9.5.4
 - Node v16.13.0

**Any other information that may help fixing the issue?**
This could be related to Optional chaining, not sure how to fix it since Node v16 and I think it should support it

**Comment by mfrachet** [comment]
Is this still an issue?

**Comment by aaron-goff** [comment]
@mfrachet I'm able to reproduce this with the following:
**Node**: 16.16.0 (also tried 16.8.0 and got the issue)
**OS**: MAC 12.5
**Cypress**: 10.4

Let me know if you need any additional information.
