### ISSUE TITLE
Update plugin to be compatible with Cypress 10

### ISSUE THREAD

**Issue by admah** [mfrachet/cypress-audit#155]
Hello 👋 I'm writing on behalf of the Cypress DX team. We wanted to notify you that some changes may need to be made to this plugin to ensure that it works in Cypress 10. 

For more information, here is our [official plugin update guide](https://cypressdx.notion.site/Cypress-10-Plugin-Update-Guide-7474129c5a3b4cc7b969d1934c5844a0).

**Comment by mfrachet** [comment]
Thanks for the heads-up, will take a look at it 😊

**Comment by mfrachet** [comment]
Updating the example to use the new API: https://github.com/mfrachet/cypress-audit/pull/156

**Comment by mfrachet** [comment]
Hello, no it's not complete yet 😊 . I'm on vacation right now and will take care of it when I'll get back! Also, I would expect the plugin to work seamlessly by moving the configuration in the new files (e.g: cypress.config.js) and making sure the command is correctly imported. 

Will update this in 2 weeks or so :)

**Comment by MichaelRobsonSliide** [comment]
> Hello, no it's not complete yet 😊 . I'm on vacation right now and will take care of it when I'll get back! Also, I would expect the plugin to work seamlessly by moving the configuration in the new files (e.g: cypress.config.js) and making sure the command is correctly imported.
> 
> Will update this in 2 weeks or so :)

Thanks for the update. I gave it a try but I ended up getting the same error as in this other open [issue](https://github.com/mfrachet/cypress-audit/issues/136) when I called lighthouse or pally. Enjoy your vacation :)

**Comment by dsueltenfuss** [comment]
Will you be updating the npm package? The latest one showing is v1.1.0

**Comment by mfrachet** [comment]
You need to install @cypress-audit/ligthouse as explained in the doc, not cypress-audit.

**Comment by dsueltenfuss** [comment]
Thank you, I missed that
