### ISSUE TITLE
Performance metric is slightly different from real chrome browser

### ISSUE THREAD

**Issue by dante01yoon** [mfrachet/cypress-audit#165]
I'm not sure this could be happened in interactive mode or not, 

the metric result  is slightly different, not sure it's worth while. 
<img width="436" alt="스크린샷 2022-06-17 오후 3 09 49" src="https://user-images.githubusercontent.com/6510430/174236160-bfeabd3b-fe48-4542-8912-7f805b8d8aec.png">
![스크린샷 2022-06-17 오후 3 11 24](https://user-images.githubusercontent.com/6510430/174236352-ac9ed06d-0982-4195-9507-5317a518b0c0.png)

**Comment by mfrachet** [comment]
This is explained in the documentation website. https://mfrachet.github.io/cypress-audit/guides/lighthouse/good-to-know.html#lighthouse-scores-may-be-different-between-local-run-and-cypress-audit
