### ISSUE TITLE
Detect browser for Pa11y to fail gracefully on browser non supporting it (like lighthouse)

### ISSUE THREAD

**Issue by blatinier** [mfrachet/cypress-audit#17]
Currently running lighthouse in a firefox test will fail gracefully with a simple log message, but Pa11y will fail the test with an error.
The behavior should be consistant I think:
 - Graceful fail on firefox, electron, etc…
 - Launch on Chrome, Chromium, etc…

**Comment by mfrachet** [comment]
I'm taking care of this, tanks for opening the issue 😊

**Comment by blatinier** [comment]
My pleasure :)
This plugin is such a great idea!

**Comment by mfrachet** [comment]
https://github.com/mfrachet/cypress-audit/pull/18
