### ISSUE TITLE
Is there any chance better formatting could be used (tabs & line breaks) so that logs in reports look better?

### ISSUE THREAD

**Issue by guillermo-abrego** [mfrachet/cypress-audit#179]
https://github.com/mfrachet/cypress-audit/blob/7bfebc733915c22d03783a0d51135500851a206d/packages/pa11y/src/command-handler.js#L48

**Comment by mfrachet** [comment]
What are your expectations?

**Comment by mfrachet** [comment]
No answers for a long time, closing for now, feel free to reopen
