### ISSUE TITLE
The Cypress port could not be resolved. Have you setup the project following this guide: 

### ISSUE THREAD

**Issue by kdp88** [mfrachet/cypress-audit#181]
EDIT:

fixed the following port issue (only) with this code in the `cypress.config.ts`

```
on('before:browser:launch', (_browser, launchOptions) => {
                prepareAudit(launchOptions);
            });
```

**What does not work?**
after following the steps found [here](https://mfrachet.github.io/cypress-audit/guides/lighthouse/installation.html#installing-the-dependency) 

I continue to get this error in both Open(`cypress open --browser chrome --e2e`) and Run mode(`npx cypress run`):

`
CypressError
cy.task('lighthouse') failed with the following error:
`

> The Cypress port could not be resolved. Have you setup the project following this guide: https://github.com/mfrachet/cypress-audit/blob/master/packages/lighthouse/README.md#preparing-the-server-configuration ?[Learn more](https://on.cypress.io/api/task)

**How to reproduce?**
I am running Cypress 10.8.0, don't really have a reproduceable example

- followed the setup in its entirety for both pa11y and lighthouse
- my baseUrl is an external url ex: https://mycompany-dev.company.com

Screenshots / Animated Gifs

![lighthouse](https://user-images.githubusercontent.com/12736081/190160309-cb480437-175f-4e8a-a003-e56a61863cc8.png)

**Environment (please complete the following information):**

- OS: Windows 10
- Chromeversion: 105
- Cypress version: 10.8.0 and 10.7.0 ( didnt try anything lower)

**Comment by mantheypw** [comment]
Commenting to say I'm also experiencing the same error in Cypress.

Current config. Is pa11y required if I just want to use Lighthouse?
![image](https://user-images.githubusercontent.com/58539225/189054713-d76a880c-b0bb-4ae6-a8db-f6a688a5f592.png)

**Comment by mfrachet** [comment]
It's the port the Cypress browser is running on. Like this line: https://github.com/mfrachet/cypress-audit/blob/53776e9654da16d68b30cce8896b487b1a87aafa/packages/shared/index.js#L7 . I don't know why, but it seems that it can't have access to it in your situation. 

You did not follow the bug template and I don't know what system you're running on.

**Comment by kdp88** [comment]
apologies, i didnt actually know if it was a bug, i can update it!

**Comment by kdp88** [comment]
fixed the following port issue (only) with this code in the `cypress.config.ts`

```
on('before:browser:launch', (_browser, launchOptions) => {
                prepareAudit(launchOptions);
            });
```
