### ISSUE TITLE
accept default no params for "cy.audit" command

### ISSUE THREAD

**Issue by bahmutov** [mfrachet/cypress-audit#2]
`cy.audit()` fails, wants at least `cy.audit({})` which is a little weird

<img width="1235" alt="Screen Shot 2020-02-19 at 11 55 40 AM" src="https://user-images.githubusercontent.com/2212006/74855646-f7c8c900-530e-11ea-9e49-e8b3a981cc7b.png">

**Comment by mfrachet** [comment]
Thanks for the report! I've just opened a PR to fix this, let me know if it fits your need 😊
