### ISSUE TITLE
Cypress Lighthouse test failing after latest Chrome Version Upgrade (Version 111.0.5563.64 )

### ISSUE THREAD

**Issue by tsathaye** [mfrachet/cypress-audit#207]
**What does not work?**
Cypress Test checking page performance metrics is failing since last week after Chrome Browser got Updated to 
Version 111.0.5563.64 
Error - 
Whoops, the Cypress extension has disconnected.
Cypress cannot run tests without this extension.

**How to reproduce?**
Reproducible with latest 12.7.0 and older Cypress version 
Is reproducible with repo https://github.com/bahmutov/cypress-lighthouse-example

**Expected behavior**
Cypress test should be able to do Lighthouse Audit

**Screenshots / Animated Gifs**
Unable to 

**Environment (please complete the following information):**
 - OS: macOS 13.0.1 (22A400)
 - Chrome version: Version 111.0.5563.64 
 - Cypress version: 12.7.0 (Also on 9.5.1)

**Any other information that may help fixing the issue?**
This was working fine until 4 days ago and started failing probably after chrome got auto upgraded.
I am trying to check if I can downgrade chrome version and run this - Will add that info if I am able to run it

**Comment by paul-s1** [comment]
I have also experienced the same. The error message is different in other Cypress versions and likely a similar issue. I was able to get it to run using Edge (Version 111.0.1661.41), although it fails the first attempt. subsequent attempts of the tests will run with results.

- OS: macOS 12.5.1
- Cypress version: 11.2.0
- Node: 18.13.0


I'm having better results when I download Chromium 110.0.5481.0 use that for browser running the test

**Comment by brandonlenz** [comment]
Seeing similar behavior. Lighthouse 1.3.1 appears to crash chrome (headless or not) with the following message:

`The automation client disconnected. Cannot continue running tests.`

<img width="683" alt="image" src="https://user-images.githubusercontent.com/15805554/225465791-1b025f12-2c6b-4d1d-9daf-5d6bd0005ba5.png">

On an older version of Cypress it was closing the browser causing a different log message in the Cypress, equivalent to closing the browser manually while testing.

**Comment by paul-s1** [comment]
@brandonlenz I also remember seeing that error, I can't remember the combination of Cypress version and Chrome version but I do remember when I ran the headless version, i was able to console.log the Lighthouse results from the first test, then it just hung. were you able to see the same?

**Comment by tsathaye** [comment]
Yes @brandonlenz - This is exact issue I was having.

@paul-s1  - I believe if you run on any other browser except Chrome the cypress test might pass however it wont do the Lighthouse Audit. I tried now again with Edge, Electron and it gave message similar to below for those browsers.

`log cy.lighthouse(), Edge is not supported. Skipping...`

**Comment by 430010838** [comment]
Based on [this issue](https://github.com/GoogleChrome/lighthouse/issues/14885) filed in the Lighthouse GitHub repo, it looks like this is an issue with `lighthouse` version 9. It looks like moving to the newly-released version 10 of `lighthouse` may correct the issue.

**Comment by bhavanareddymahakala** [comment]
I am observing the same issue, it was working for me with cypress version 6 & chrome version 111 but we have upgraded to cypress 12.7.0 and since then lighthouse test are erroring out with the same above attached screenshot.

**Comment by 430010838** [comment]
FYI I tested upgrading this package to version `^10.0.2` of `lighthouse` and it worked. The breaking changes announced for version 10 [here](https://github.com/GoogleChrome/lighthouse/releases/tag/v10.0.0) don't seem to affect this package's functionality much.

**Comment by ofeigenbaum** [comment]
<img width="2118" alt="image" src="https://user-images.githubusercontent.com/122781274/226607612-7d2d3aa2-3ef8-43d1-9b01-6ebd12da5f7c.png">
still having the same issue

**Comment by 430010838** [comment]
It looks like the author of the last PR [mentioned](https://github.com/mfrachet/cypress-audit/pull/209#issuecomment-1477335578) he was still seeing issues with this after his latest changes went it. 

In my local testing for moving this library to `lighthouse@10.0.2`, I had to change the `require()` statement in `task.js` to pull in the CommonJS module version of `lighthouse` since they converted the default import the ESM as part of the major verison 10 release. If issues are still being observed, we may need to tweak [this line](https://github.com/mfrachet/cypress-audit/blob/master/packages/lighthouse/src/task.js#L1) to be `require('lighthouse/core/index.cjs')` instead. You can see release notes [here](https://github.com/GoogleChrome/lighthouse/releases/tag/v10.0.0)), specifically this part:

```
Converted from CommonJS to ES modules. You can still use lighthouse in CommonJS by using an dynamic import: await import('lighthouse'). For access to just the lighthouse function in CommonJS, you can also use require('lighthouse/core/index.cjs')
```

**Comment by mfrachet** [comment]
Yeah, I had issues also between ESM and commonjs. Not sure which one to pick since I suppose to every project is different

I can do both, but I ll be forced to release two different majors.

And I don't have that much time to maintain this library as you can see

**Comment by mfrachet** [comment]
Should be fixed in 1.4.1 can you confirm?

**Comment by MuckT** [comment]
@mfrachet my tests using `cy.pa11y` and `cy.lighthouse` are now working on 1.4.1 🚀

**Comment by mfrachet** [comment]
Thanks again for your help 🙏🏻

**Comment by ofeigenbaum** [comment]
1.145s omerfeigenbaum ❯ npm i @cypress-audit/lighthouse
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:*

**Comment by mfrachet** [comment]
humf, since there's not build step implied, the module tries to resolve the sibling folder that is not shipped. I'll take a look tomorrow morning 🤦🏻

**Comment by mfrachet** [comment]
Should be fixed in 1.4.2 sorry for that

**Comment by tsathaye** [comment]
Thanks @mfrachet for the releasing 1.4.2

**After upgrading dependencies to following** 
"@cypress-audit/lighthouse": "^1.4.2",
"@cypress-audit/pa11y": "^1.4.2",
"cypress": "^12.8.1",

**I am NOT getting the error**
The Cypress extension has disconnected.
Cypress cannot run tests without this extension.

**However now the test is failing with below**

cy.task('lighthouse') failed with the following error:
> Unexpected token '||='[Learn more](https://on.cypress.io/api/task)
[node_modules/@cypress-audit/lighthouse/src/command-handler.js:46:1](https://www.ajbell.co.uk/__/#)
  44 |     cy.log("-------- cy.lighthouse --------");
  45 |     return cy
> 46 |       .task("lighthouse", {
     | ^
  47 |         url,
  48 |         thresholds: thresholds || configThresholds || defaultThresholds,
  49 |         opts: opts || globalOptions,
  ------------------------------------------------------------

Is there any change required in the calling function?
Or is this a separate issue which needs to be logged?

**Comment by MuckT** [comment]
@tsathaye have you tried removing you node modules with `rm -rf ./node_modules` and then reinstalling?

**Comment by mfrachet** [comment]
This repository https://github.com/mfrachet/cypress-audit/tree/master/examples :)

**Comment by tsathaye** [comment]
Cool - Thanks 
Let me check it out

**Comment by tsathaye** [comment]
I tried the above repo also tried to replicate that in our test - However wasn't able to get it working 

1. Then I created a sample repo https://github.com/tsathaye/lighthouseaudit 
2. Copied files & single test from **NextJS Example folder**
3. Last thing I did was update the test to use http://cypress.io/ as base url

And am still getting the same error in this repo too - Can you please review when you have a moment 

Thanks,
Tushar

**Comment by mfrachet** [comment]
I honestly don't know what's going on, your repo works on my side 😓 

<img width="1440" alt="Screenshot 2023-03-30 at 7 56 58 AM" src="https://user-images.githubusercontent.com/3874873/228742968-c6f58ac6-ee40-49ff-a951-4fc47800f0cf.png">

**Comment by TheDeadWeatcher** [comment]
had the same issue, this settings help me, in cypress 12.9V working well,

https://mfrachet.github.io/cypress-audit/guides/lighthouse/installation.html#installing-the-dependency

![lighthouse](https://user-images.githubusercontent.com/121101613/228833962-63b2afcd-73be-408a-a172-2564163fdcf6.png)

**Comment by MuckT** [comment]
@tsathaye have you tried clearing your Cypress cache: [troubleshooting](https://docs.cypress.io/guides/references/troubleshooting#Clear-Cypress-cache).

**Comment by tsathaye** [comment]
Yes @MuckT - Tried clearing / reinstalling Cypress on my Mac now however the issue persists. :(

**Comment by MuckT** [comment]
@tsathaye I've tried your branch locally and it's working well. Have you tried force a remote install of the repos?
`npm install --force`?

```
Running:  homepage.cy.js                                                                  (1 of 1)


  The App
    1) audits the home page


  0 passing (38s)
  1 failing

  1) The App
       audits the home page:
     Error: cy.lighthouse - A threshold has been crossed.

performance record is 36 and is under the 50 threshold
```

**Comment by tsathaye** [comment]
Thanks @mfrachet @MuckT - I probably should have done this sooner. :( 
https://github.com/tsathaye/lighthouseaudit started working after upgrading node 

`"@cypress-audit/lighthouse": "^1.4.2",
    "@cypress-audit/pa11y": "^1.4.2",
    "cypress": "^12.9.0"`

And with following 

npm -v  9.5.1
node -v  = v18.16.0
