### ISSUE TITLE
Missing link to repo on npmjs.com

### ISSUE THREAD

**Issue by aaxenger** [mfrachet/cypress-audit#22]
Tried to find this repo from https://www.npmjs.com/package/cypress-audit however the link is not there. My guess is this could be rectified by adding the `repository` element to package.json but it might take more.

By the way, there is a broken link in the [README here](https://github.com/mfrachet/cypress-audit/blame/master/README.md#L81). Looks like there is a missing file under the docs folder.

Super useful plugin, thank you!

**Comment by mfrachet** [comment]
Thanks for opening this issue! I just pushed a fix concerning what you mentioned 😊 

Happy you like it and feel free to share if you see that could improve and benefit from the community!

Thanks again and have a great day / evening :D
