### ISSUE TITLE
QUESTION: Reporting metrics e.g. "First Contentful Paint"

### ISSUE THREAD

**Issue by canakg** [mfrachet/cypress-audit#24]
From the documentation I see how to check scores, such as Performance and SEO.

I would like to also be able to assert on underlying metrics, such as First Contentful Paint etc. Is it possible with this tool?

**Comment by mfrachet** [comment]
Hello there :) . Is this something that Lighthouse 6 is able to report?

While it's not for now, if the answer to my question is yes, then we can probably do something :)

**Comment by canakg** [comment]
Hi @mfrachet 
It is reported by Lighthouse 6 (See https://web.dev/lighthouse-whats-new-6.0/#new-metrics ).

I have tried to implement it myself, but for some reason I can't figure out the console log for the raw lighthouse report is not working for me at all, that's why I am having trouble figuring that out. Would appreciate your help :)

**Comment by mfrachet** [comment]
That sounds awesome! I should definitely look at these 😊 . Thanks for helping here!

**Comment by mfrachet** [comment]
This should be available in the `0.2.2` release :). I'm closing the issue but let me know if it works for you! I've added some information in the readme if you'd like more infos :)
