### ISSUE TITLE
It could report numbers even if there is no threshold

### ISSUE THREAD

**Issue by bahmutov** [mfrachet/cypress-audit#3]
`cy.audit({})` just says all good - but I want to see the results to know what to set as a baseline

<img width="1142" alt="Screen Shot 2020-02-19 at 11 56 08 AM" src="https://user-images.githubusercontent.com/2212006/74855734-13cc6a80-530f-11ea-8065-4e25012f1da3.png">

**Comment by mfrachet** [comment]
Also thank you for the report, I've opened a PR to display the different scores for successful (and not successful) test suites 😊 . Let me know if it fits your need 😄
