### ISSUE TITLE
Impossible to set a different pa11y runner or use the pa11y "standard" flag?

### ISSUE THREAD

**Issue by rswerve** [mfrachet/cypress-audit#32]
The docs say that we should be able to pass pa11y options to `cy.pa11y()`, but the "standard" flag doesn't have any effect, and trying to set "runners" causes Cypress to crash.  I believe this line might be responsible: https://github.com/mfrachet/cypress-audit/blob/master/src/a11y/task.js#L10
```javascript
pa11yLib(url, { browser, runners: ["axe"], ...opts }).then((results) => {
```

**Comment by benjamindavid** [comment]
I'm observing the same kind of behavior where `threshold` and `standard` options don't seem to be taken into account.

**Comment by benjamindavid** [comment]
It looks like using the `htmlcs` allows you to use the `standard` option:
```js
{
    runners: ['htmlcs'],
    standard: 'Section508',
}
```

The `axe` runner probably doesn't support that `standard` option.

But that doesn't solve the `threshold` issue. I couldn't find any reference of that option in `pa11y/lib/pa11y.js`, only `pa11y/bin/pa11y.js` uses it, so I'm thinking it's probably a CLI feature only.

**Comment by rswerve** [comment]
Oh, thanks @benjamindavid, I had mistakenly passed a string to `runners`.  But I also can't get `threshold` to work.

**Comment by mfrachet** [comment]
I've also tried to put the threshold as close as possible to the pa11y lib call and I didn't manage to make them work 😬 .

**Comment by rswerve** [comment]
Threshold isn't very important to me personally.  By the way, this project has helped really streamline our testing; thanks for making it.

**Comment by mfrachet** [comment]
Thank you so much for the kind words, means a lot to me 🙏

**Comment by mfrachet** [comment]
I'm closing this for now, feel free to ask for reopen if necessary 😊

**Comment by kussmaul** [comment]
I had (and figured out) a related issue. I set `standard` to 'WCAG2AAA' and `ignore` to an array of WCAG standards, which worked correctly in `pa11y` and `pa11y-ci`, but had no effect in `@cypress-audit/pa11y`.
pa11y docs note that `standard` is only used by the `htmlcs` runner.

I eventually figured out that `runners` defaults to `[ 'axe' ]` (in `@cypress-audit/pa11y`):
https://github.com/mfrachet/cypress-audit/blob/2e098be6e01dfea9a4e6896e0efa068f141e5ed9/packages/pa11y/src/task.js#L11
but to `[ 'htmlcs' ]` in `pa11y` and `pa11y-ci`:
https://github.com/pa11y/pa11y?tab=readme-ov-file#runners-array

When I added `runners : [ 'htmlcs' ]` to my `cypress-audit/pa11y` config, everything worked!
