### ISSUE TITLE
Any ideas for supporting typescript/angular?

### ISSUE THREAD

**Issue by trfulcher** [mfrachet/cypress-audit#36]
Your project looks really cool. I have an angular app using cypress via the Nrwl.io setup, but I'm stuck running this. I did the installation as suggested then tried to workaround the absence of  @types/cypress-audit by faking an index.d.ts declaration but when I run I still get 

```Oops...we found an error preparing this test file:

  src\support\index.ts

The error was:

Error: Webpack Compilation Error
E:/git/b2c/apps/appcheck-e2e/src/integration/app.spec.ts
ERROR in E:/git/b2c/apps/appcheck-e2e/src/integration/app.spec.ts(26,8):
TS2339: Property 'lighthouse' does not exist on type 'cy & EventEmitter'.

E:/git/b2c/apps/appcheck-e2e/src/integration/app.spec.ts
ERROR in E:/git/b2c/apps/appcheck-e2e/src/integration/app.spec.ts(27,8):
TS2339: Property 'pa11y' does not exist on type 'cy & EventEmitter'.
```

Any ideas?

Tim

**Comment by mfrachet** [comment]
Woops, looks I'm missing some d.ts files in the project :D. Will do! thanks for the interest 😊

**Comment by mfrachet** [comment]
as a temporary workaround, you can cast it as any: `(cy as any).lighthous()`

**Comment by snehalka** [comment]
@mfrachet  I tried the temporary workaround mentioned above but it's running into a different issue.
<img width="744" alt="Screenshot 2020-12-01 at 9 50 05 PM" src="https://user-images.githubusercontent.com/25681478/98732007-dd53e580-239e-11eb-9bd6-c0450e75e9ca.png">

**Comment by mfrachet** [comment]
Have you followed the 3 steps for the installation?

**Comment by connorbrez** [comment]
@mfrachet I am also having some issues using this on an angular project with the above work around, I added the commands to my own index.d.ts as well but the same issue occurred. 

<img width="1004" alt="Screen Shot 2020-11-27 at 6 53 19 PM" src="https://user-images.githubusercontent.com/1653982/100490556-dd175200-30e1-11eb-9923-484c920059a3.png">

**Comment by mfrachet** [comment]
IIRC, `index.d.ts` is a type definition file.  I think that you may have to import it in the actual implementation command file.

Also, what you could do is to create an open source project showing this issue so that I can play with it and help you :)

**Comment by mfrachet** [comment]
v0.2.4 ships an index.d.ts file owning some declarations for typescript. Make sure to have:

```ts
/// <reference path="cypress-audit" />
```

at the top of your cypress tests and should be good to go :).

I'm closing the issue for now, feel free to reopen if you're in trouble :)

**Comment by Kranthi-Kick** [comment]
> as a temporary workaround, you can cast it as any: `(cy as any).lighthouse()`

I'm facing issue in using cy.lighthouse() 
<img width="667" alt="Screenshot 2021-04-05 at 8 47 19 PM" src="https://user-images.githubusercontent.com/62151799/113592179-71766000-9652-11eb-858f-36c22202165e.png">
