### ISSUE TITLE
Headless mode

### ISSUE THREAD

**Issue by Tgralak** [mfrachet/cypress-audit#38]
Is there any way to run this in headless mode?
What I want to achieve is logging the results on cy dashboard during cypress run.

**Comment by mfrachet** [comment]
Hey there! I'll be more than happy to help 👍🏻 

However, I've never used Cypress Dashboard. Could you give me more context on what can not be done with this library in the dashboard?

**Comment by Tgralak** [comment]
In order to store tests on dashboard, I need to run cypress through `npx cypress run` which is headless.
As far as I know, cypress-audit generates reports only while I run tests through `npx cypress open`.
I want to store some metrics from lighthouse every time I run my tests locally. It's easy to achieve in the pipeline, but I need to do it before and more frequently

**Comment by mfrachet** [comment]
This library works in headless mode like: https://github.com/mfrachet/cypress-audit/blob/master/example/package.json#L20 .

Right now, the only way to access lighthouse output metric is to use the following: https://github.com/mfrachet/cypress-audit#accessing-the-raw-reports

**Comment by Tgralak** [comment]
Thanks a lot, I managed to publish my results straight into dashboard.

**Comment by arifmasood** [comment]
@Tgralak can you share approach you used to publish lighthouse results in dashboard.
It would be great help for me or anyone who comes here looking for this :)

**Comment by minologyVN** [comment]
> This library works in headless mode like: https://github.com/mfrachet/cypress-audit/blob/master/example/package.json#L20 .
> 
> Right now, the only way to access lighthouse output metric is to use the following: https://github.com/mfrachet/cypress-audit#accessing-the-raw-reports

Could you share more details about run cypress audit under cypress headless mode ? The link you provide does not exist
