### ISSUE TITLE
Error: You probably have multiple tabs open to the same origin.

### ISSUE THREAD

**Issue by arvigeus** [mfrachet/cypress-audit#39]
```
cy.task('lighthouse') failed with the following error:
> You probably have multiple tabs open to the same origin.

node_modules/cypress-audit/src/performances/commands.js:34:1
  32 | 
  33 |     cy.log("-------- cy.lighthouse --------");
> 34 |     cy.task("lighthouse", {
     | ^
  35 |       url,
  36 |       thresholds: thresholds || configThresholds || defaultThresholds,
  37 |       opts,
```

cypress: 6.0.1
cypress-audit: 0.2.3
Repo: https://github.com/katawaredev/permisisve-nextjs-template
(note: some of the packages there are not available in npm, if you need to run it I'll tweak it)

Reproducing:

```json
"scripts": {
    "prod": "run-s build start",
    "test:e2e": "start-test prod 3000 'TZ=UTC cypress run'",
    "e2e": "start-test prod 3000 'TZ=UTC cypress open'"
  },
```

Running `test:e2e` (headless mode) does not produce errors, but running `e2e` (UI) does

**Comment by mfrachet** [comment]
This shouldn't be an issue 🤔 . Do you have a record of a test to show what's going on the screen?

And if you're able to provide a repo that I can work with (in your case, moving to dependencies I can install) that would be awesome :).

Thanks for the issue opeening

**Comment by arvigeus** [comment]
Here's a full repo: https://github.com/arvigeus/cypress-audit-issue

`npm test` passes, but `npm run e2e` complains.

Thanks!

(and awesome project, btw)

**Comment by arvigeus** [comment]
Hmmm, I think this issue is unrelated to this project.

https://github.com/GoogleChrome/lighthouse/issues/3024

**Comment by mfrachet** [comment]
Hey there! Thanks for the kind words and the issue. I can repro locally :). I'm going to investigate a little and give you feedbacks as soon as I can :)

**Comment by mfrachet** [comment]
As an update: I managed to replicate the error. And at some point, I decided to clear the cypress cache  by passing `{ disableStorageReset: false }` as option. Then, I re-run the test another time without this option and it looked to work 🤔 

I'm not sure what's going on here. I've added a nextjs example in the example so that we can make verifications on this in CI / locally, but I have to admit that I have no idea what's going on here 😅

**Comment by mfrachet** [comment]
Has this been resolved somehow or is this still a thing?

**Comment by arvigeus** [comment]
I haven't had time to check your solution, but it seems right. Thanks a lot! 👍

**Comment by fredicious** [comment]
> Has this been resolved somehow or is this still a thing?
> 
> EDIT: in my case, this was due to a service worker that was registered and breaks the origin thing :o. I've unregister it and then it worked again :o

thanks, it's 2023 and your solution still fixed the issue for me
