### ISSUE TITLE
cypress-audit(lighthouse) not matching results of chrome lighthouse for performance

### ISSUE THREAD

**Issue by fbarquero** [mfrachet/cypress-audit#40]
When running cypress-audit in a test as cy.lighthouse('www.google.com') the result related to performance is not matching the result of the lighthouse chrome plugin:
![image](https://user-images.githubusercontent.com/6843693/100920489-cdf92100-34a0-11eb-9f72-97792272879b.png)

Lighthouse plugin result:
![image](https://user-images.githubusercontent.com/6843693/100920443-be79d800-34a0-11eb-9d41-3f9a96f14531.png)

Test:
describe('using lightouse with cypress www.google.com', { taskTimeout: 120000 }, () => {

it('Should access www.google.com and perform lighthouse assessment', () => {
    cy.visit('https://www.google.com')
    cy.lighthouse({
        performance: 1,
        accessibility: 85,
        'best-practices': 85,
        //seo: 85,
        //pwa: 30,
      },
      {
        disableStorageReset: true , 
        emulatedFormFactor: "desktop"
    })
})
})

plugin implementation:
const { lighthouse, pa11y, prepareAudit } = require("cypress-audit");

module.exports = (on, config) => {
on("before:browser:launch", (browser = {}, launchOptions) => {
prepareAudit(launchOptions);
})

on("task", {
lighthouse: lighthouse((lighthouseReport) => {
console.log('LighthouseReport: '+lighthouseReport)
}), // calling the function is important
pa11y: pa11y((pa11yReport) => {
console.log(pa11yReport); // raw pa11y report
}), // calling the function is important
})
}

**Comment by mfrachet** [comment]
I don't have a proper answer to this one. This library "just" runs the lighthouse command on a Cypress browser, nothing more :( . I hope you can find more information about number differences on the lighthouse repo

**Comment by arifmasood** [comment]
@fbarquero I was facing the same and after some search and experimentation, I concluded that it is related to lighthouse-api itself. You can use any online available tools (debug-bear, foo.software etc) that are dependent on lighthouse-api and their numbers will be much closer to numbers generated by "cypress-audit".

Some other factors that may impact on scores can be:

- lighthouse version version used by devtools, plugin or tools - same or not
- cookies, indexDB being cleared properly or not - use incognito
- throttle, location, device settings are same or not

**Comment by mfrachet** [comment]
Thanks @arifmasood for your help here. I'm closing since I think your answer is the most relevant. Feel free to reopen if necessary 😊
