### ISSUE TITLE
Bug: You probably have multiple tabs open to the same origin.

### ISSUE THREAD

**Issue by vrknetha** [mfrachet/cypress-audit#63]
I keep on getting this error when running against this website. It works fine when I use this plugin using playwright.

https://github.com/abhinaba-ghosh/playwright-lighthouse

But, i use cypress much rather than playwright and i need these tests. Please look into it. i have made a repo so that it could be easy to reproduce the issue.Here is my repo

https://github.com/vrknetha/cypress-lighthouse

![image](https://user-images.githubusercontent.com/20596261/106462425-11c9d000-64bc-11eb-88f3-c55a642e0215.png)

**Comment by mfrachet** [comment]
I know what's going wrong. And it's probably related to https://github.com/mfrachet/cypress-audit/issues/62 . But I don't know how to fix this.

Running in headless mode should pass however (I think)

**Comment by mfrachet** [comment]
Can you make sure to be on cypress 6.4.0 and followed https://docs.cypress.io/guides/references/trade-offs.html#Same-origin ?

Would you mind giving feedback after that please 🙏🏻 😊 ?

**Comment by mfrachet** [comment]
Well, I think I can close this issue for now, feel free to reopen it if you're still facing the issue 😊

**Comment by isair** [comment]
This exact error also happens when a service worker is registered. Manually clearing application storage from Chrome works, but only for the next test. Using Next with next-pwa.
