### ISSUE TITLE
Can't find out how to customise pa11y options

### ISSUE THREAD

**Issue by eloisetaylor5693** [mfrachet/cypress-audit#66]
One setting I would love to know if it exists is a failure threshold:  if less than the threshold, then succeed, othewise fail test.

**Comment by mfrachet** [comment]
For now, this module only accepts the different pa11y options exposed by the library: https://github.com/pa11y/pa11y#configuration

What kind of threshold are referring to? Number of failing tests? Putting whitelist of errors?

**Comment by mfrachet** [comment]
Closing this for not being active in about 20 days. Feel free to reopen if necessary
