### ISSUE TITLE
lighthouse check is being skipped with command line

### ISSUE THREAD

**Issue by evanhooff** [mfrachet/cypress-audit#73]
**What does not work?**
When running the cypress test command line, the test is skipped with the message 'Electron is not supported' and it stops as if the test is passed. But when I run the test with the cypress dashboard, the test fails as expected.
I don't know where to begin looking to fix this..

**How to reproduce?**
I only have a basic setup of cypress-audit:

plugin:
```
const { lighthouse, prepareAudit } = require("cypress-audit");
module.exports = (on, config) => {
  on("before:browser:launch", (browser = {}, launchOptions) => {
    prepareAudit(launchOptions);
  });
  on('task', {
    lighthouse: lighthouse((lighthouseReport) => { // calling the function is important
      console.log(lighthouseReport); // raw lighthouse reports
    }),
    log(message) {
      console.log(message)
      return null
    },
    table(message) {
      console.table(message)
      return null
    }
  })
}
```

integration:
```
it("should pass the audits", function () {
    cy.visit('/')
    const threshold = {
        "performance": 100,
        "accessibility": 100,
        "best-practices": 100,
        "seo": 100,
        "pwa": 100
    }
    cy.lighthouse(threshold);
});
```

and run this with `npm cypress run`

**Expected behavior**
I expect when I run the test via terminal/command line to have the same result as when it's run from the dashboard.

**Screenshots / Animated Gifs**
Screenshot from the video output of the command line test:
![image](https://user-images.githubusercontent.com/24935712/111186395-4482e000-85b3-11eb-9549-2d31b7e3e98b.png)

Screenshot from the test in the cypress dashboard:
![image](https://user-images.githubusercontent.com/24935712/111187158-0a660e00-85b4-11eb-98d6-df2edecc4b0c.png)

**Environment (please complete the following information):**
 - OS: Windows
 - Chrome version: 89.0.4389.82
 - Cypress version: 5.2.0

**Comment by mfrachet** [comment]
When running Cypress, you can test on different environments such as [Electron](https://www.electronjs.org/), Chrome, Firefox and eventually Edge.

The problem that you're facing is that [Lighthouse](https://developers.google.com/web/tools/lighthouse/), the underlying tool that I'm using to make the assertions only runs on Chrome, and so, cypress-audit just skips the tests on Electron.

In order to see the same thing on your Cypress UI and on the Cypress dashboard, you will have to change your environment from Electron to Chrome. If I remember correctly when you run the cypress command that opens the GUI, you should see a dropdown on the top right corner with "Electron" selected. You can try to choose something else and run the tests again 😊

**Comment by evanhooff** [comment]
Hi, thanks for your quick response!

Aah, of course, there is no browser running. When I look at the settings it says:
"When I look at the settings, it says that Electron is de default browser that comes with Cypress. This is de default browser that runds in headless mode."

But I checked the selected browser in my GUI, it already has 'Crome' selected, so I guess I need to see if I can change the default browser in headless mode.  

![image](https://user-images.githubusercontent.com/24935712/111280928-ae939780-863c-11eb-89e0-24655e5acef1.png)

Thank you so much, I now know where to look to resolve this issue. 
If I have it, I will post :)

**Comment by evanhooff** [comment]
The answer is you need to add the browser to the command.
And for use in CI, you need to use a docker image.

It's here in the documentation:
https://docs.cypress.io/guides/guides/launching-browsers.html#Chrome-Browsers

**Comment by RickMeasham** [comment]
I think it's worth adding the requirement for `--browser chrome` in the main docs. I had to hunt through closed tickets to find this!

**Comment by japneetlambdatest** [comment]
This fails if we pass path of binary in --browser option
