### ISSUE TITLE
Cannot destructure property 'errors' of 'object null' as it is null

### ISSUE THREAD

**Issue by rakeshsukla53** [mfrachet/cypress-audit#74]
I am trying to run a very basic cypress audit test and seeing this issue `Cannot destructure property 'errors' of 'object null' as it is null.`

<img width="611" alt="Screen Shot 2021-03-28 at 3 41 09 PM" src="https://user-images.githubusercontent.com/9192661/112765627-08e90c80-8fdc-11eb-801e-11b169d17836.png">

spec file 

```
describe("External", () => {
  it("check scores", () => {
    cy.visit("https://google.com/");

    cy.lighthouse({
      accessibility: 50,
      "best-practices": 50,
      seo: 50,
      pwa: 50,
    });
  });
});
```

**chrome version** - 89

**cypress and cypress-audit version** - 
```    
"cypress": "^6.4.0",
 "cypress-audit": "^0.3.0",
```

**index.js file**
```
const { lighthouse, pa11y, prepareAudit } = require("cypress-audit");

module.exports = (on, config) => {
  on("before:browser:launch", (browser = {}, launchOptions) => {
    prepareAudit(launchOptions);
    return launchOptions;
  });

  on("task", {
    lighthouse: lighthouse((lighthouseReport) => {
      console.log(lighthouseReport);
    }), // calling the function is important
  });
};

```

Will appreciate if you could share your thoughts on this. Thank you

**Comment by rakeshsukla53** [comment]
Some debugging notes: `Port is undefined` in my case so the function is not getting called
```
const lighthouse = (callback) => ({ url, thresholds, opts = {}, config }) => {
  if (port) {
    opts.port = port;

    if (!opts.onlyCategories) {
      opts.onlyCategories = Object.keys(thresholds);
    }

    if (opts.disableStorageReset === undefined) {
      opts.disableStorageReset = true;
    }

    return lighthouseLib(url, opts, config).then((results) => {
      if (callback) {
        callback(results);
      }

      const computedAudits = computeAudits(results.lhr.audits);
      const computedCategories = computeCategories(results.lhr.categories);

      const allMetrics = { ...computedAudits, ...computedCategories };

      return compareWithThresholds(allMetrics, thresholds);
    });
  }
  return null;
};
```

**Comment by rakeshsukla53** [comment]
`cypress-audit` expects a remote debugging port set by user if it's not supplied the function is returning `null`

**Comment by rakeshsukla53** [comment]
I am using chrome 89 and it seems like this block of code is not getting executed. This should run just before launching the browser but  I don't see any logging in the node server. Not sure what's going on here!!
```
on('before:browser:launch', (browser = {}, launchOptions) => {
  /* ... */
})
```

@mfrachet I will reach out to Cypress to understand more about this and appreciate any thoughts from your side

**Comment by rakeshsukla53** [comment]
The issue in my case was coming from cypress code coverage report package. I will close this issue.

**Comment by Greg-D-Robertson** [comment]
@rakeshsukla53  I also have this issue.  Do you mind expanding on the issue you had with your code coverage report package and how you overcame it?  Thanks!

**Comment by omartaghlabi** [comment]
@rakeshsukla53 hi, how did you end up resolving this issue?
