### ISSUE TITLE
Is it possible to separate the pa11y from others, it has a different license and it may cause issue when we do not need it but it is in the dependency.  

### ISSUE THREAD

**Issue by LauraLHZ** [mfrachet/cypress-audit#75]
https://github.com/mfrachet/cypress-audit/blob/b8cce1e261d18d7c627221a8b88ea245eabcc813/package.json#L13

**Comment by mfrachet** [comment]
I did not plan to do so. Is the license thing a problem you're facing?

**Comment by eshperber** [comment]
I'm facing the same issue regarding licensing of pa11y

**Comment by eric-burel** [comment]
Not an expert but according from the sumamry of Pa11y license it expects you to make your code open source, so not suited for most projects indeed.

**Comment by mfrachet** [comment]
I'll try to take a look when I have some spare time 😊 . Thanks for the heads-up

**Comment by eric-burel** [comment]
Thank you, because the lib is awesome otherwise :) Works right out of the box and finally include Lighthouse in our normal testing workflow without having to setup a complex CI. It even works in headless mode as far as I can tell, which I wasn't expecting.

**Comment by mfrachet** [comment]
Okay, I've spent my lunch on this :D. If you check the https://github.com/mfrachet/cypress-audit again, it's updated. Basically, there are now 2 packages: @cypress-audit/lighthouse and @cypress-audit/pa11y.

They both have their dedicated readme file :). Let me know if it helps for your test scenarios.

I'm closing this issue in the meantime, feel free to reopen if it's still an issue. Thanks 👋🏻 😊

**Comment by eric-burel** [comment]
Brilliant package, thank you!!
