### ISSUE TITLE
Cypress 7.2.0 Upgrade, Import is Not a Module for cypress-audit

### ISSUE THREAD

**Issue by NihinFaj** [mfrachet/cypress-audit#83]
**What does not work?**
I have just upgraded Cypress for my automation project from 6.2.1 to 7.2.0, when I attempt to run the project with the command `npm run cypress:open ` I get the error below. When I check my index.ts file in the plugin folder, my import from cypress-audit gives the error **_File 'C:/REPO/AutomationProject/node_modules/cypress-audit/index.d.ts'_** is not a module. 

I have deleted node_modules and installed multiple times. My cypress-audit version in my package.json is cypress-audit@0.3.0

Can someone please look into this to see what the problem is?

**How to reproduce?**
- Upgrade to cypress 7.2.0
- Use **import { lighthouse, pa11y, prepareAudit } from 'cypress-audit'** in the index.ts file in the plugins folder
- You should get a similar error **_File 'c:/REPO/bp-rio-test-automation/node_modules/cypress-audit/index.d.ts' is not a module._**

**Expected behaviour**
The import should be successful and not throw an error 

**Screenshots / Animated Gifs**
<img width="799" alt="one" src="https://user-images.githubusercontent.com/22470370/117545008-d2130700-b01b-11eb-842a-4316bef0fbc4.PNG">

<img width="399" alt="two" src="https://user-images.githubusercontent.com/22470370/117545018-da6b4200-b01b-11eb-85b4-236b2acdbdaa.PNG">

**Environment (please complete the following information):**
 - OS: Windows 10
 - Chrome version: Version 90.0.4430.93 (Official Build) (64-bit)
 - Cypress version: 7.2.0
 - Cypress-audit version: 0.3.0

**Comment by mfrachet** [comment]
Thanks for reporting, will investigate 😊

**Comment by mfrachet** [comment]
I've bumped cypress to 7.3 in the example folder, and I don't have errors with the NX one (which is built in typescript) 🤔 

<img width="1280" alt="VSCode with a test file opened showing the cy.lighthouse command example when hovering the command itself" src="https://user-images.githubusercontent.com/3874873/118441753-eb861400-b6e9-11eb-9127-ee7ab6dcff79.png">

Would you mind providing a repro example so that I can play with it?

**Comment by NihinFaj** [comment]
Unfortunately I cannot share a sample repo, as the repo I have the problem on is a private repo :(

**Comment by mfrachet** [comment]
It's not possible for you to repro on another project? Could it be possible that it's a problem with your project? Not sure how I can help you if I'm not able to repro on my end 😅
